[package]
name = "rust-template"
version = "0.1.0"
authors = ["BuRny <gamingburny@gmail.com>"]
edition = "2018"

[lib]
name = "my_library"
crate-type = ["dylib"]

[dependencies]
cute = "0.3.0"

[profile.dev]
opt-level = 3
