name: Rust

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        rust: [nightly]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: |
        cargo clean
        cargo build --release
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: target/release
